"""Map verbatim Excel branch names to ``salary_branches.id`` UUIDs.

The Excel files store branch labels in many forms — short bare
(``"Карпатський"``), short with suffix (``"Карпатський лісовий офіс"``),
quoted-and-prefixed (``'Філія "Карпатський лісовий офіс"'``), and even
footnote-suffixed (``'філія "Лісовий навчальний центр"**'``). All map
to the same canonical branch row through ``salary_branch_aliases``.

DB-side, ``salary_branch_aliases.alias_normalized`` is auto-populated
from ``alias_raw`` by trigger ``tr_branch_alias_normalize``, which
calls ``fn_normalize_indicator_name``. Python-side resolver must use
the **same** normalization to look up by ``alias_normalized``. This
module owns the mirror.

If the DB function ever changes, update both ``_normalize_branch_name``
here AND the parametrized table in ``tests/db/test_branch_resolver.py``
together — the table is the source of truth for parity.
"""
from __future__ import annotations

import re
from typing import Any
from uuid import UUID

# Pre-compiled patterns mirror the four ``regexp_replace`` calls in
# fn_normalize_indicator_name. Order matters — see the SQL function
# definition for the canonical sequence.
_RE_TYPO_TSEN = re.compile(r"цін реалізації")
_RE_VAT_SUFFIX = re.compile(r"\(без пдв\)")
_RE_TRAILING_STAR = re.compile(r"\*+$")
_RE_RUNS_OF_WS = re.compile(r"\s+")


def _normalize_branch_name(name: str) -> str:
    """Mirror of DB-side ``fn_normalize_indicator_name`` for branch names.

    Produces the value that matches
    ``salary_branch_aliases.alias_normalized`` (auto-generated by the
    ``tr_branch_alias_normalize`` trigger using
    ``fn_normalize_indicator_name`` on every INSERT/UPDATE).

    Steps in lockstep with the SQL function:
      1. lowercase
      2. ``"цін реалізації" → "ціна реалізації"``
         (no-op for branches but mirrored for parity).
      3. strip ``"(без пдв)"`` substring (no-op for branches, mirrored).
      4. strip trailing ``\\*+`` — KEY for footnote-suffixed names like
         ``'філія "Лісовий навчальний центр"**'``.
      5. collapse runs of whitespace into single spaces.
      6. trim outer whitespace.

    If the DB function ever changes, update this mirror AND the unit
    test in ``tests/db/test_branch_resolver.py`` simultaneously.
    """
    s = name.lower()
    s = _RE_TYPO_TSEN.sub("ціна реалізації", s)
    s = _RE_VAT_SUFFIX.sub("", s)
    s = _RE_TRAILING_STAR.sub("", s)
    s = _RE_RUNS_OF_WS.sub(" ", s)
    return s.strip()


def resolve_branch_id(cur: Any, branch_name: str) -> UUID | None:
    """Look up ``salary_branches.id`` for a verbatim Excel branch name.

    Normalizes via ``_normalize_branch_name`` (DB regex mirror) then
    SELECTs from ``salary_branch_aliases`` where ``alias_normalized``
    matches.

    Returns ``None`` when no alias matches — callers must warn and
    skip the salary row (sub-step 5.4.4 design decision: human-reviewed
    addition of new branch spellings via SQL, not auto-INSERT).

    ``cur`` is a psycopg2 cursor (typed as ``Any`` to avoid hard import
    of psycopg2 from this module — keeps the resolver testable without
    a live DB).
    """
    norm = _normalize_branch_name(branch_name)
    cur.execute(
        "SELECT branch_id FROM salary_branch_aliases WHERE alias_normalized = %s",
        (norm,),
    )
    row = cur.fetchone()
    return UUID(str(row[0])) if row else None


__all__ = ["_normalize_branch_name", "resolve_branch_id"]
